name: auth_repository
description: Authentication provider.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  auth_api:
    path:
      ../auth_api
  dartz: ^0.10.1

dev_dependencies:
  mocktail: ^1.0.5
  test: ^1.31.1
  very_good_analysis: ^10.2.0
