name: qatar2022_stickers
description: Take control of your FIFA World Cup stickers album.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.3.22

dependencies:
  auth_repository:
    path: ./packages/auth_repository

  bloc: ^8.1.4
  collection: ^1.18.0

  equatable: ^2.0.5
  firebase_auth: ^4.19.6
  firebase_auth_api:
    path: ./packages/firebase_auth_api

  firebase_core: ^2.31.1
  firebase_database: ^10.5.6
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter

  form_inputs:
    path: ./packages/form_inputs

  formz: ^0.7.0

  friends_repository:
    path: ./packages/friends_repository

  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  
  isar_stickers_api:
    path: ./packages/isar_stickers_api

  local_storage_stickers_api:
    path: ./packages/local_storage_stickers_api

  rtdb_friends_api:
    path: ./packages/rtdb_friends_api
  rtdb_stickers_api:
    path: ./packages/rtdb_stickers_api

  scrollable_positioned_list: ^0.3.8
  share_plus: ^9.0.0
  stickers_repository:
    path: ./packages/stickers_repository
  
  ui:
    path: ./packages/ui
  

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
