name: in_memory_auth_api
description: Implementation of auth_repository_api.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auth_api:
    path:
      ../auth_api
  crypto: ^3.0.2

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
