name: in_memory_auth_api
description: Implementation of auth_repository_api.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  auth_api:
    path:
      ../auth_api
  crypto: ^3.0.7

dev_dependencies:
  mocktail: ^1.0.5
  test: ^1.31.1
  very_good_analysis: ^10.2.0
