name: firebase_auth_api
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auth_api:
    path: ../auth_api

  crypto: ^3.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  google_sign_in: ^5.2.3
  meta: ^1.7.0
  sign_in_with_apple: ^4.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
