name: isar_stickers_api
description: stickers_api implementation using Isar Database
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  isar: ^3.0.2

  stickers_api:
    path:
      ../stickers_api

dev_dependencies:
  build_runner: ^2.3.0
  isar_generator: ^3.0.2
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
