name: isar_stickers_api
description: stickers_api implementation using Isar Database
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  isar: ^3.1.0+1

  stickers_api:
    path:
      ../stickers_api

dev_dependencies:
  build_runner: ^2.4.10
  isar_generator: ^3.1.0
  mocktail: ^1.0.3
  test: ^1.19.2
  very_good_analysis: ^5.1.0
